version: '3.8'
services: 
  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=adm
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=teste
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local